[package]
name = "betyg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.0.29"
csv = "1.1.6"
eyre = "0.6.8"
serde = { version = "1.0.148", features = ["derive"] }
